modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/Laton95/Pyramid-Plunder/issues"
logoFile="pyramidplunder.png"

[[mods]]
modId="pyramidplunder"
version="${version}"
displayURL="https://minecraft.curseforge.com/projects/pyramid-plunder"
displayName="Pyramid Plunder"
authors="Laton95"
description='''
A simple treasure mod inspired by the Runescape minigame Pyramid Plunder.
'''

[[dependencies.pyramidplunder]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"